
name: Build-WakeOnLan

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #   - uses: actions/checkout@v4  # Use the latest version of setup-node
    #     with:
    #         repository: Florianisme/WakeOnLan
    #         # path: my-tools

      - uses: actions/checkout@v4

      - name: Checkout Source Code
        run: |
            git clone --depth 1 https://github.com/Florianisme/WakeOnLan Florianisme/WakeOnLan
            mv -f Florianisme/WakeOnLan/* ./
            rm -rf Florianisme/WakeOnLan
            rm -rf wear

      - name: Set up JDK and Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 -d > app/kt.jksx
          echo "" >> gradle.properties
          echo "UPLOAD_KEYSTORE_PATH=app/kt.jksx" >> gradle.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}" >> gradle.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> gradle.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> gradle.properties

      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew --parallel --max-workers=8 bundlerelease assemblerelease


      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/TVBox/
          find . -name "*.apk" -exec mv {} ${{ github.workspace }}/TVBox/ \;
          
        #   for file in `find ~ \( -name "*.apk" -o -name "*java*.apk" \) -not -name "*x86*" -print`; do
        #     base=$(basename "$file")
        #     new_base="WakeOnLan_$base"
        #     mv "$file" "TVBox/$new_base"
        #   done

        #   ls TVBox/*.apk


      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WakeOnLan
          path: ${{ github.workspace }}/TVBox/*.apk


    #   - name: Release APP
    #     uses: softprops/action-gh-release@v2
    #     with:
    #       name: FongMi-TVBox
    #       tag_name: FongMi-TVBox
    #       files: |
    #         TVBox-TV/media/apk/*.apk