name: Build-dart_simple_live

on:
  workflow_dispatch:
  push:

jobs:
  # 打包Android、iOS、Mac
  build-mac-ios-android:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      # 签出代码
      - uses: actions/checkout@v4
        with:

      - name: Checkout Source Code
        run: |
          git clone --depth 1 -b dev https://github.com/xiaoyaocz/dart_simple_live.git simple_live_tv


      # 设置JAVA环境
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: "gradle"

      # 设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true 

      # 打开MAC Desktop支持
      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop

      # 更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_tv/simple_live_app
          flutter pub get

      # 安装appdmg npm install -g appdmg
      - name: Install appdmg
        run: npm install -g appdmg

      # 设置flutter_distributor环境
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor


      # TV APK签名设置
      - name: Create key.properties
        run: |
          echo "storeFile=${{ github.workspace }}/.github/workflows/TVBoxOSC.jks" > simple_live_tv/simple_live_tv_app/android/key.properties
          echo "storePassword=TVBoxOSC" >> simple_live_tv/simple_live_tv_app/android/key.properties
          echo "keyPassword=TVBoxOSC" >> simple_live_tv/simple_live_tv_app/android/key.properties
          echo "keyAlias=TVBoxOSC" >> simple_live_tv/simple_live_tv_app/android/key.properties

      #打包 Android TV APK
      - name: Build TV APK
        run: |
          cd simple_live_tv/simple_live_tv_app
          flutter build apk --release --split-per-abi

      #上传TV APK至Artifacts
      - name: Upload TV APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_tv
          path: |
            simple_live_tv/simple_live_tv_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_tv/simple_live_tv_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_tv/simple_live_tv_app/build/app/outputs/flutter-apk/app-x86_64-release.apk

  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Delete workflow runs
      uses: AoThen/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3